"""
core/state_manager.py — Central, thread-safe application state.

All services read from and write to this single source of truth.
Uses threading.Lock for mutation and exposes Python properties so the UI
and services can react to state changes via the event bus.
"""
import threading
from dataclasses import dataclass, field
from typing import Optional


# ---------------------------------------------------------------------------
# Data Classes
# ---------------------------------------------------------------------------

@dataclass
class LiveStats:
    """Real-time champion statistics from the Live Client API activePlayer.championStats."""
    armor: float = 0.0
    magic_resist: float = 0.0
    max_health: float = 0.0
    current_health: float = 0.0
    attack_damage: float = 0.0
    ability_power: float = 0.0
    ability_haste: float = 0.0
    crit_chance: float = 0.0
    attack_speed: float = 0.0
    tenacity: float = 0.0
    life_steal: float = 0.0
    lethality: float = 0.0

@dataclass
class DraftAction:
    """A single pick or ban action in the draft phase."""
    champion_name: str = ""     # resolved from champion map (English)
    is_ally: bool = True        # True = blue side team, False = enemy
    is_ban: bool = False        # True = ban, False = pick
    is_locked: bool = False     # True = locked/completed
    is_my_action: bool = False  # True = this is my pick/ban slot


@dataclass
class ChampSelectState:
    """Snapshot of the current champ-select session."""
    in_champ_select: bool = False
    my_champion_id: int = 0
    my_champion_name: str = ""
    my_position: str = ""          # top / jungle / middle / bottom / utility
    is_my_pick_turn: bool = False   # True only when it's MY turn to pick
    is_my_ban_turn: bool = False    # True when it's MY turn to ban
    my_ban_action_id: int = 0       # LCU action ID for my ban
    is_finalization_phase: bool = False # True when all picks are locked
    ally_champion_names: list[str] = field(default_factory=list)
    enemy_champion_names: list[str] = field(default_factory=list)
    banned_champion_names: list[str] = field(default_factory=list)
    
    # ── New attributes for ban recommendation ──
    my_hover: str = ""
    ally_hovers: list[str] = field(default_factory=list)
    ally_ban_intents: list[str] = field(default_factory=list)
    my_recent_picks: dict[str, list[str]] = field(default_factory=dict)
    
    draft_actions: list[DraftAction] = field(default_factory=list)
    last_advice: str = ""
    # Champion suggestions (3 pre-generated by AI)
    suggestions: list[str] = field(default_factory=list)       # English names
    suggestion_reasons: list[str] = field(default_factory=list)  # Short reasons
    
    # Ban recommendations (Top 3)
    ban_suggestions: list[str] = field(default_factory=list)
    ban_reasons: list[str] = field(default_factory=list)


@dataclass
class PlayerInGameData:
    """Stats for a single player extracted from the Live Client API."""
    riot_id: str = ""
    champion_name: str = ""
    team: str = ""            # "ORDER" or "CHAOS"
    position: str = ""        # TOP / JUNGLE / MID / ADC / SUPPORT ("" si non fourni)
    level: int = 1
    kills: int = 0
    deaths: int = 0
    assists: int = 0
    cs: int = 0
    gold: int = 0
    items: list[int] = field(default_factory=list)
    is_local_player: bool = False
    is_dead: bool = False
    respawn_timer: float = 0.0

    @property
    def kda_ratio(self) -> float:
        return (self.kills + self.assists) / max(1, self.deaths)

    @property
    def is_fed(self) -> bool:
        """
        Simple 'fed' heuristic:
        - Kills >= 5 AND deaths <= 2 (snowballing hard early)
        - OR KDA ratio >= 3.0 (consistently performing)
        """
        return (self.kills >= 5 and self.deaths <= 2) or self.kda_ratio >= 3.0


@dataclass
class InGameState:
    """Snapshot of the current in-game session."""
    in_game: bool = False
    game_time_seconds: float = 0.0
    local_player: Optional[PlayerInGameData] = None
    all_players: list[PlayerInGameData] = field(default_factory=list)
    fed_enemies: list[PlayerInGameData] = field(default_factory=list)
    threat_vector: dict[str, float] = field(default_factory=dict)
    live_stats: Optional[LiveStats] = None
    last_item_advice: str = ""
    last_item_advice_for_champion: str = ""


@dataclass
class AppState:
    """Root application state container."""
    # Connection status
    lcu_connected: bool = False
    live_client_connected: bool = False
    game_phase: str = "NONE"   # "NONE" | "CHAMP_SELECT" | "IN_GAME" | "POST_GAME"

    # Sub-states
    champ_select: ChampSelectState = field(default_factory=ChampSelectState)
    in_game: InGameState = field(default_factory=InGameState)

    # Summoner identity (resolved once at startup)
    puuid: str = ""
    summoner_name: str = ""


# ---------------------------------------------------------------------------
# State Manager
# ---------------------------------------------------------------------------

class StateManager:
    """Thread-safe wrapper around AppState."""

    def __init__(self) -> None:
        self._state = AppState()
        self._lock = threading.Lock()

    # -----------------------------------------------------------------------
    # Generic access
    # -----------------------------------------------------------------------

    def get(self) -> AppState:
        """Return a shallow copy of the current state (thread-safe read)."""
        with self._lock:
            import copy
            return copy.deepcopy(self._state)

    def update_lcu_connected(self, value: bool) -> None:
        with self._lock:
            self._state.lcu_connected = value

    def update_live_client_connected(self, value: bool) -> None:
        with self._lock:
            self._state.live_client_connected = value

    def update_game_phase(self, phase: str) -> None:
        with self._lock:
            self._state.game_phase = phase

    # -----------------------------------------------------------------------
    # Champ Select
    # -----------------------------------------------------------------------

    def update_champ_select(self, new: ChampSelectState) -> None:
        with self._lock:
            self._state.champ_select = new
            self._state.game_phase = "CHAMP_SELECT" if new.in_champ_select else self._state.game_phase

    def set_champ_select_advice(self, advice: str) -> None:
        with self._lock:
            self._state.champ_select.last_advice = advice

    # -----------------------------------------------------------------------
    # In-Game
    # -----------------------------------------------------------------------

    def update_in_game(self, new: InGameState) -> None:
        with self._lock:
            self._state.in_game = new
            if new.in_game:
                self._state.game_phase = "IN_GAME"

    def set_item_advice(self, advice: str, for_champion: str) -> None:
        with self._lock:
            self._state.in_game.last_item_advice = advice
            self._state.in_game.last_item_advice_for_champion = for_champion

    # -----------------------------------------------------------------------
    # Identity
    # -----------------------------------------------------------------------

    def set_summoner(self, puuid: str, name: str) -> None:
        with self._lock:
            self._state.puuid = puuid
            self._state.summoner_name = name
